project:
  type: website
  output-dir: docs

website:
  title: "Pesquisa Meros SC"
  navbar:
    logo: meroiconwhite.png
    left:
      - text: "Manuais"
        menu:
          - text: "SeaGIS CAL"
            href: index.qmd
          - text: "EventMeasure"
            href: eventmeasure.qmd
      - text: "Protocolos de Campo"
        menu:
          - text: "BRUV"
            href: bruv.qmd
          - text: "Plano de EmergÃªncia"
            href: emergence.qmd
  back-to-top-navigation: true

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

