project:
  type: website
  output-dir: docs

date: 05/02/2026
date-format: long
website:
  title: "Projeto Meros do Brasil"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    number-sections: true
    theme:
      - cerulean
      - brand
    css: styles.css

editor: visual

