project:
  type: website
  output-dir: docs

website:
  title: "Pesquisa Meros SC"
  navbar:
    logo: meroiconwhite.png
    left:
      - text: "Manuais"
        menu:
          - text: "SeaGIS CAL"
            href: index.qmd
          - about.qmd
      - text: "Protocolos de Campo"
        menu:
          - text: "Bruv"
            href: bruv.qmd


page-layout: full
format:
  html:
    toc: true
    toc-title: "√çndice"
    toc-location: right
    toc-expand: true
    toc-depth: 2
    smooth-scroll: false
    number-sections: true
    theme:
      - cerulean
      - brand
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

